Sources/KProcess.KL2.WebAdmin/Models/Audit/AuditItemViewModel.cs
using KProcess.Ksmed.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KProcess.KL2.WebAdmin.Models.Audit
{
    public class AuditItemViewModel
    {
        public int AuditId { get; set; }
        public int Number { get; set; }
        public string Question { get; set; }
        public bool? IsOK { get; set; }
        public bool HasPhoto { get; set; }
        public string Photo { get; set; }
        public string RawPhoto { get; set; }
        public string Comment { get; set; }
    }
}

Sources/KProcess.KL2.WebAdmin/Models/Audit/AuditManageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KProcess.KL2.WebAdmin.Models.Audit
{
    public class AuditManageViewModel
    {
        public AuditManageViewModel()
        {
            Audits = new List<AuditViewModel>();
        }
        public IEnumerable<AuditViewModel> Audits { get; set; }
    }
}

Sources/KProcess.KL2.WebAdmin/Models/Audit/AuditSummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KProcess.KL2.WebAdmin.Models.Audit
{
    public class AuditSummaryViewModel
    {
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public int Month { get; set; }
        public int Total { get; set; }
        public string stringTotal { get; set; }
        public string Color { get; set; }
    }
}

Sources/KProcess.KL2.WebAdmin/Models/Audit/AuditViewModel.cs
using KProcess.KL2.WebAdmin.Models.Inspection;
using KProcess.Ksmed.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace KProcess.KL2.WebAdmin.Models.Audit
{
    [Serializable]
    public class AuditViewModel
    {
        public int? AuditId { get; set; }
        public int SurveyId { get; set; }
        public string SurveyName { get; set; }
        public int AuditorId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public List<AuditItemViewModel> AuditItems { get; set; }
        public int AuditeeId { get; set; }


        public int InspectionId { get; set; }
        public string ProcessName { get; set; }
        public string AuditorName { get; set; }
        public string AuditeeName { get; set; }
        public List<string> AuditorTeams { get; set; }
        public bool IsOK { get; set; }
        public InspectionViewModel Inspection { get; set; }
        public int AnomalyNumber { get; set; }
        
        public List<string> SurveyQuestions { get; set; }
    }
}

Sources/KProcess.KL2.WebAdmin/Controllers/AuditController.cs
using KProcess.KL2.JWT;
using KProcess.KL2.Languages;
using KProcess.KL2.WebAdmin.Authentication;
using KProcess.KL2.WebAdmin.Identity;
using KProcess.KL2.WebAdmin.Mapper;
using KProcess.KL2.WebAdmin.Models.Audit;
using KProcess.Ksmed.Business;
using KProcess.Ksmed.Models;
using KProcess.Ksmed.Security;
using Syncfusion.EJ.Export;
using Syncfusion.JavaScript.Models;
using Syncfusion.XlsIO;
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace KProcess.KL2.WebAdmin.Controllers
{
    [CustomAuthorize(KnownRoles.Administrator, KnownRoles.Supervisor, KnownRoles.Technician, KnownRoles.Documentalist)]
    [SettingUserContextFilter]
    public class AuditController : LocalizedController
    {
        readonly IApplicationUsersService _applicationUsersService;
        readonly IPrepareService _prepareService;
        readonly IReferentialsService _referentialsService;

        List<AuditViewModel> auditViewModel;
        List<AuditItemViewModel> auditItemViewModel;

        public int count;
        public string grid;

        public AuditController(
            IApplicationUsersService applicationUsersService,
            IPrepareService prepareService,
            IReferentialsService referentialsService,
            ILocalizationManager localizationManager
            )
            : base(localizationManager)
        {
            _applicationUsersService = applicationUsersService;
            _prepareService = prepareService;
            _referentialsService = referentialsService;
        }

        // List of audits
        [CustomAuthorize(KnownRoles.Administrator, KnownRoles.Supervisor, KnownRoles.Technician, KnownRoles.Documentalist)]
        public async Task<ActionResult> Index(int? userId, bool partial = false)
        {
            UserModel user = JwtTokenProvider.GetUserModel(Request.Cookies["token"].Value);
            if (!userId.HasValue && !user.Roles.Any(r => (new[] { KnownRoles.Administrator, KnownRoles.Supervisor, KnownRoles.Documentalist }.Contains(r))))
                return RedirectToAction("Index", new { userId = user.UserId, partial = partial });
            var audits = await _prepareService.GetAudits();
            if (userId.HasValue)
            {
                audits = audits.Where(a => a.AuditorId == userId.Value || a.Inspection.InspectionSteps.Any(s => s.InspectorId == userId.Value));
            }           

            var model = AuditMapper.ToAuditManageViewModel(audits);
            if (partial)
                return PartialView(model);
            return View(model);
        }


        public async Task<ActionResult> Detail(int? id, bool partial = false)
        {
            UserModel user = JwtTokenProvider.GetUserModel(Request.Cookies["token"].Value);
            var audits = await _prepareService.GetAudits(id);
            if (!audits.Any())
                return HttpNotFound();
            var audit = audits.First();
            if (!user.Roles.Any(r => (new[] { KnownRoles.Administrator, KnownRoles.Supervisor, KnownRoles.Documentalist }.Contains(r))) && audit.AuditorId != user.UserId && !audit.Inspection.InspectionSteps.Any(s => s.InspectorId == user.UserId))
                return RedirectToAction("Index", new { userId = user.UserId, partial = partial });
            var inspection = await _prepareService.GetInspection(audit.InspectionId);

            var inspectionSteps = InspectionController.GetInspectionStepAndChilds(inspection, inspection.Publication.PublishedActions.Distinct()
                    .OrderBy(a => a.WBSParts, new WBSPartsComparer()).ToList());
            var anomalies = await _prepareService.GetAnomalies(audit.InspectionId);
            var model = AuditMapper.ToAuditViewModel(audits.FirstOrDefault());
            model.Inspection = InspectionMapper.ToInspectionViewModel(inspection, inspectionSteps, anomalies.ToList());
            if (partial)
                return PartialView(model);
            return View(model);
        }

        [CustomAuthorize(KnownRoles.Administrator, KnownRoles.Supervisor, KnownRoles.Documentalist)]
        public async Task<ActionResult> AuditSummary(DateTime? month, bool partial = false)
        {
            var (users, roles, languages, teams) = await _applicationUsersService.GetUsersAndRolesAndLanguages();
            List<Team> allTeams = teams.OrderBy(t => t.Name).ToList();
            var audits = await _prepareService.GetAudits();
            if (month == null)
            {
                month = DateTime.Now;
            }
            audits = audits.Where(a => a.EndDate.Value.Month == month.Value.Month && a.EndDate.Value.Year == month.Value.Year);
            ViewBag.selectedMonth = month;
            List<AuditSummaryViewModel> model = new List<AuditSummaryViewModel>();
            if (audits.Any(a => !a.Auditor.Teams.Any()))
            {
                var total = audits.Count(a => !a.Auditor.Teams.Any());
                model.Add(new AuditSummaryViewModel
                {
                    TeamId = -1,
                    TeamName = LocalizedStrings.GetString("WithoutTeam"),
                    Total = total,
                    stringTotal = total.ToString(),
                    Color = total <= 1 ? "#FC1919" : "#07C900"
                });
            }
            foreach (var team in allTeams)
            {
                var total = audits.Count(a => a.Auditor.Teams.Any(t => t.Id == team.Id));
                model.Add(new AuditSummaryViewModel {
                    TeamId = team.Id,
                    TeamName = team.Name,
                    Total = total,
                    stringTotal = total.ToString(),
                    Color = total <= 1 ? "#FC1919" : "#07C900"
                });
            }
            if (partial)
                return PartialView(model);
            return View(model);
        }

        /// <summary>
        /// Verify ans creare an audit if possible
        /// </summary>
        /// <param name="InspectionId"></param>
        /// <param name="SurveyId"></param>
        /// <returns></returns>
        public async Task<JsonResult> VerifyAndCreateAudit(int InspectionId, int SurveyId)
        {
            try
            {
                UserModel user = JwtTokenProvider.GetUserModel(Request.Cookies["token"].Value);
                var result = await _prepareService.GetActiveAudit(user.UserId);
                if (result != null)
                    return Json(new { verified = false }, JsonRequestBehavior.AllowGet);

                var newAudit = new Audit
                {
                    SurveyId = SurveyId,
                    AuditorId = user.UserId,
                    InspectionId = InspectionId,
                    StartDate = DateTime.Now
                };
                var audit = await _prepareService.SaveAudit(newAudit);
                return Json(new { verified = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                var message = string.Join(" | ", ModelState.Values
                     .SelectMany(v => v.Errors)
                     .Select(e => e.ErrorMessage));
                return Json(new { verified = false, message = ex.Message }, JsonRequestBehavior.AllowGet);
            }
            
        }

        public async Task ExportToExcel(string GridModel, string gridId, int id, string process, int? userId)
        {
            ExcelExport exp = new ExcelExport();
            GridProperties obj = (GridProperties)Syncfusion.JavaScript.Utils.DeserializeToModel(typeof(GridProperties), GridModel);
            //Clear if there are any filter columns
            //syncfusion bug in exporting while in filter mode
            obj.FilterSettings.FilteredColumns.Clear();
            grid = gridId;
            count = 0;

            if (gridId == "Audits")
            {
                var audits = await _prepareService.GetAudits();
                if (userId.HasValue)
                {
                    audits = audits.Where(a => a.AuditorId == userId.Value || a.Inspection.InspectionSteps.Any(s => s.InspectorId == userId.Value));
                }
                var auditManage = AuditMapper.ToAuditManageViewModel(audits);
                //var dataSource = auditManage.Audits.ToList();
                //auditViewModel = dataSource;
                //var currentDate = DateTime.Today.ToShortDateString().Replace("/", "-");
                //obj.ServerExcelQueryCellInfo = QueryCellInfo;
                //exp.Export(obj, dataSource, "Audits " + currentDate + ".xlsx", ExcelVersion.Excel2013, false, false, "flat-saffron");

                using (ExcelEngine excelEngine = new ExcelEngine())
                {
                    // Set the default application version as Excel 2016. 
                    excelEngine.Excel.DefaultVersion = ExcelVersion.Excel2016;


                    //var group1 = auditManage.Audits.ToList();
                    var allAudits = auditManage.Audits.ToList();
                    int i = 0;
                    //Create a workbook with a worksheet. 
                    IWorkbook workbook = excelEngine.Excel.Workbooks.Create(audits.Select(a => a.Survey).Distinct().Count());

                    foreach (var survey in audits.Select(a => a.Survey).Distinct())
                    {
                        IWorksheet worksheet = workbook.Worksheets[i];
                        DataTable tbl = new DataTable();
                        //fill columns
                        tbl.Columns.Add(LocalizedStrings.GetString("AuditDate"), typeof(string));
                        tbl.Columns.Add(LocalizedStrings.GetString("Schedule"), typeof(string));
                        tbl.Columns.Add(LocalizedStrings.GetString("Team"), typeof(string));
                        tbl.Columns.Add(LocalizedStrings.GetString("Auditor"), typeof(string));

Sources/KProcess.KL2.WebAdmin/Views/Audit/AuditSummary.cshtml
@using Syncfusion.EJ2.Charts;
@using KProcess.KL2.WebAdmin.Models.Audit;
@using System.Globalization;
@using KProcess.KL2.Languages;

@model List<AuditSummaryViewModel>

@{
    var LocalizedStrings = (ILocalizationManager)ViewBag.LocalizedStrings;
    ViewBag.Title = "AuditSummary";
    TextInfo textInfo = new CultureInfo("en-US", false).TextInfo;
    DateTime filter = ViewBag.selectedMonth;
    var month = textInfo.ToTitleCase(DateTimeFormatInfo.CurrentInfo.MonthNames.ToList().ElementAt(filter.Month - 1));
    var year = filter.Year;
}

<style>
    .filterBar {
        display: inline-block;
        vertical-align: middle;
        float: none;
        margin-bottom: 10px;
    }
</style>

<div class="innerContainer">
    <div class="innerHeader">
    </div>
    <div class="innerContent">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm("AuditSummary", "Audit", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "onFilter(event)" }))
                {
                    <div class="filterBar">
                        @(Html.EJS().DatePicker("month")
                            .Start(Syncfusion.EJ2.Calendars.CalendarView.Year)
                            .Depth(Syncfusion.EJ2.Calendars.CalendarView.Year)
                            .Format("MMM-yyyy")
                            .Value(ViewBag.selectedMonth)
                            .Render()
                        )
                    </div>
                    <div class="filterBar">
                        @(Html.EJS().Button("filterBtn")
                            .Content(LocalizedStrings.GetString("Filter"))
                            .Render()
                        )
                    </div>
                }
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @(Html.EJS().Chart("AuditSummary")
                    .Series(series =>
                    {
                        series.Type(Syncfusion.EJ2.Charts.ChartSeriesType.Column)
                            .Name(LocalizedStrings.GetString("TotalAudits"))
                            .XName("TeamName")
                            .YName("Total")
                            .DataSource(Model)
                            .Marker(mr => mr.DataLabel(dl => dl.Visible(true).Name("stringTotal").Position(LabelPosition.Top).Font(new { fontWeight = "600", color = "#ffffff" })))
                            .PointColorMapping("Color")
                            .Add();
                    })
                    .PrimaryXAxis(px =>
                    {
                        px.ValueType(Syncfusion.EJ2.Charts.ValueType.Category)
                            .MajorGridLines(m => m.Width(0.00001))
                            .Interval(1)
                            .LabelIntersectAction(LabelIntersectAction.Wrap);
                    })
                    .PrimaryYAxis(py =>
                    {
                        py.Minimum(0)
                            .Maximum(12)
                            .Interval(3)
                            .LineStyle(l => l.Width(0.00001))
                            .LabelStyle(l => l.Color("transparent"))
                            .MajorGridLines(m => m.Width(0.00001))
                            .MajorTickLines(m => m.Width(0.00001));
                    })
                    .EnableSideBySidePlacement(false)
                    .Title(LocalizedStrings.GetStringFormat("Web_AuditSummaryMonthlyTitle", month, year.ToString()))
                    .ChartArea(area => area.Border(new ChartBorder { Color = "transparent" }))
                    .Tooltip(tt => { tt.Enable(true).Shared(true); })
                    .Render()
                )
            </div>
        </div>
    </div>
</div>

<script>
    docReady(function () {
        setHeader("@LocalizedStrings.GetString("Web_Menu_Audit")" + "/" + "@LocalizedStrings.GetString("Web_Menu_AuditMonitoring")");
        setIsRefreshing(false);
    });
    function onFilter(event) {
        event = event || window.event || event.srcElement;
        event.preventDefault();
        var month = document.getElementById("month").ej2_instances[0].value;
        var link = "/Audit/AuditSummary?partial=True&month=-1";
        link = link.replace("-1", month.toString());
        LoadPartial(link, '#pageContainer');
    }
</script>

@Html.EJS().ScriptManager()

Sources/KProcess.KL2.WebAdmin/Views/Audit/Index.cshtml
@using KProcess.KL2.WebAdmin.Models.Audit;
@using System.Web.Mvc.Html;
@using KProcess.KL2.JWT;
@using KProcess.KL2.Languages;

@model AuditManageViewModel

@{
    var LocalizedStrings = (ILocalizationManager)ViewBag.LocalizedStrings;
    ViewBag.Title = "Index";
    UserModel user = JwtTokenProvider.GetUserModel(Request.Cookies["token"].Value);
    var ejLanguageCode = "en";
    var currentUserLanguageCode = JwtTokenProvider.GetUserModelCurrentLanguage(Request.Cookies["token"].Value);
    if (currentUserLanguageCode != null)
    {
        ejLanguageCode = currentUserLanguageCode.ToString().Split('-')[0];
    }
    else
    {
        if (user.DefaultLanguageCode != null)
        {
            ejLanguageCode = user.DefaultLanguageCode.Split('-')[0];
        }
    }
}

<style>
    .readCell {
        background-color: lightgreen;
    }

    .notReadCell {
        background-color: lightcoral;
    }

    <style > .filterBar {
        display: inline-block;
        vertical-align: middle;
        float: none;
        padding-bottom: 10px;
    }

    .filterBar > .filterBtn {
        margin-top: 23px;
    }

    .notOK {
        background-color: lightcoral;
    }
</style>

<div class="innerContainer">
    <div class="innerHeader">
    </div>
    <div class="innerContent">
        @{
            if (Model.Audits.Count() != 0)
            {
                @(Html.EJS().Grid("Audits")
                            .DataSource(ds => ds.Json(Model.Audits.ToArray()).Adaptor("RemoteSaveAdaptor"))
                            .GridLines(Syncfusion.EJ2.Grids.GridLine.Both)
                            .AllowPaging()
                            .PageSettings(p => p.PageSize(25))
                            .Locale(ejLanguageCode)
                            //Excel export
                            .AllowExcelExport()
                            .ExcelQueryCellInfo("excelQueryCellInfo")
                            .AllowTextWrap()
                            .AllowFiltering()
                            .FilterSettings(f => f.Type(Syncfusion.EJ2.Grids.FilterType.Excel))
                            .EnableHover()
                            .Toolbar(new List<string>() { "ExcelExport" })
                            .ToolbarClick("toolbarClick")
                            .Columns(col =>
                            {
                                col.Field("AuditId").IsPrimaryKey(true).HeaderText("Id").Visible(false).IsIdentity(true).Width(5).Add();
                                col.Field("ProcessName").HeaderText(LocalizedStrings.GetString("Inspection")).Template("#linkAudit").MinWidth("140px").AllowFiltering(true).AllowSorting(true).TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Add();
                                col.Field("AuditorName").HeaderText(LocalizedStrings.GetString("Auditor")).Width(200).AllowFiltering(false).TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Add();
                                col.Field("AuditorTeams").HeaderText(LocalizedStrings.GetString("AuditorTeam")).Width(200).AllowFiltering(true).AllowSorting(true).TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Add();
                                col.Field("AuditeeName").HeaderText(LocalizedStrings.GetString("Auditee")).Width(200).AllowFiltering(false).TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Add();
                                col.Field("SurveyName").HeaderText(LocalizedStrings.GetString("Questionnaire")).Width(200).AllowFiltering(true).AllowSorting(true).TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Add();
                                col.Field("EndDate").HeaderText(LocalizedStrings.GetString("AuditDate")).Format("yMd").Width(200).AllowFiltering(true).TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Add();
                                col.Field("AnomalyNumber").HeaderText(LocalizedStrings.GetString("AnomalyNumber")).Width(200).AllowFiltering(false).TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Add();
                                col.Field("IsOK")
                                    .HeaderText(LocalizedStrings.GetString("Result")).TextAlign(Syncfusion.EJ2.Grids.TextAlign.Center)
                                    .Visible(false)
                                    .Width(200).AllowFiltering(false).Add();
                            })
                            .DataBound("gridDataBound")
                            .RecordDoubleClick("recordDblClick")
                            .QueryCellInfo("gridQueryCellInfo")
                            .RowSelecting("onSelectingCheck")
                            .Load("gridLoad")
                            .Render()
                )
            }
            else
            {
                @Html.Label(LocalizedStrings.GetString("NoAuditAvailable"));
            }
        }
    </div>
</div>

<script type="text/template" id="linkAudit">
    <a class="linkAudit" onclick="GoToDetail(${AuditId})" href="javascript:void(0)">${ProcessName}</a>
</script>

<script type="text/javascript">
    docReady(function () {
        setHeader("@LocalizedStrings.GetString("Web_Menu_Audit")" + "/" + "@LocalizedStrings.GetString("AuditList")");
        setIsRefreshing(false);
        refreshLicenseExpiredStatus(@(ViewBag.LicenseExpired != null ? ViewBag.LicenseExpired.ToString().ToLower() : false));
        applyReadOnlyIfExpired();
    });

    function gridDataBound(args) {
        this.autoFitColumns(['EndDate', 'AnomalyNumber']);
    }

    function GoToDetail(auditId) {
        LoadPartial('/Audit/Detail?id=' + auditId + '&partial=true', '#pageContainer');
    }

    function gridCreate(args) {
        var textWidth = $(".orientationcss > div").outerWidth();//Obtain the width of the headerText content.
        $(".e-headercell").css("height", 125); //Assign the obtained textWidth as the height of the headerCell
        $(".e-stackedHeaderCell").css("height", 50);
    }
    function gridLoad(args) {
        var len = this.columns.length;
        for (var i = 0; i < len; i++) {
            if (this.columns[i].field.includes("date") || this.columns[i].field.includes("Date"))
                this.columns[i].format = { type: 'date', format: 'dd/MM/yyyy' }; //apply the format to corresponding date column
        }
    }
    function gridQueryCellInfo(args) {
        if (args.data.IsOK == false) {
            args.cell.classList.add('notOK');
        }
        if (args.column.field == "AuditorTeams") {
            var teams = args.data["AuditorTeams"];
            args.cell.innerText = String(teams).replace(/\,/g, ', ');
        }
    }
    function recordDblClick(args) {
        GoToDetail(args.rowData["AuditId"]);
    }
    function excelQueryCellInfo(args) {
        if (args.data.IsOK == false) {
            args.style = { backColor: '#F08080' };
        }
    }
    function toolbarClick(args) {
        if (args.item.id === 'Audits_excelexport') {
            var gridObj = document.getElementById("Audits").ej2_instances[0];
            var excelExportProperties = {
                fileName: "Audits.xlsx"
            };
            gridObj.excelExport(excelExportProperties);
        }
    }
</script>

@Html.EJS().ScriptManager()