Sources/KProcess.KL2.WebAdmin/Controllers/ActionController.cs
using KProcess.KL2.Languages;
using KProcess.KL2.WebAdmin.Authentication;
using KProcess.KL2.WebAdmin.Identity;
using KProcess.KL2.WebAdmin.Mapper;
using KProcess.KL2.WebAdmin.Models.Action;
using KProcess.Ksmed.Business;
using KProcess.Ksmed.Models;
using KProcess.Ksmed.Security;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KProcess.KL2.WebAdmin.Controllers
{
    [CustomAuthorize(KnownRoles.Administrator, KnownRoles.Supervisor, KnownRoles.Evaluator, KnownRoles.Trainer, KnownRoles.Technician, KnownRoles.Operator, KnownRoles.Documentalist)]
    [SettingUserContextFilter]
    public class ActionController : LocalizedController
    {
        readonly IPrepareService _prepareService;
        readonly IApplicationUsersService _applicationUsersService;
        readonly IReferentialsService _referentialsService;
        
        public ActionController(IPrepareService prepareService,
            IApplicationUsersService applicationUsersService,
            IReferentialsService referentialsService,
            ILocalizationManager localizationManager
            )
            : base(localizationManager)
        {
            _prepareService = prepareService;
            _applicationUsersService = applicationUsersService;
            _referentialsService = referentialsService;
        }

        /// <summary>
        /// Show more information about an action
        /// Routing create to be able to access as: /Action/Id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<ActionResult> Details(int? PublishModeFilter, int? id, bool computeReadNext=false, bool partial = false)
        {
            if (!id.HasValue)
                return HttpNotFound();

            var action = await _prepareService.GetPublishedAction(id.Value);
            if (action == null)
                return HttpNotFound();

            var publication = await _prepareService.GetLightPublication(action.Publication.PublicationId);

            ViewBag.ComputeReadNext = computeReadNext;
            ViewBag.publishModeFilter = PublishModeFilter.Value;

            // TODO : Faire le calcul du chemin critique en incluant les tâches des sous-process
            // Change to normal WBS order (alphanumeric)
            //if (computeReadNext)
            //{
            //    var tempCriticalPath = publication.PublishedActions.CriticalPath(p => p.Successors, p => p.BuildFinish - p.BuildStart);
            //    var criticalPath = new List<PublishedAction>();
            //    for (int i = tempCriticalPath.Count(); i > 0; i--)
            //        criticalPath.Add(tempCriticalPath.ElementAt(i - 1));

            //    var nextActionIndex = criticalPath.IndexOf(criticalPath.First(u => u.PublishedActionId == id)) + 1;
            //    ViewBag.NextAction = nextActionIndex >= criticalPath.Count ? 0 : criticalPath[nextActionIndex].PublishedActionId;

            //}
         

            var actionIndex = action.Publication.PublishedActions.OrderBy(a => a, new WBSComparer()).Select(p => p.PublishedActionId).ToList().IndexOf(action.PublishedActionId);
            var previousId = actionIndex - 1 >= 0 ? action.Publication.PublishedActions.OrderBy(a => a, new WBSComparer()).Select(p => p.PublishedActionId).ToList().ElementAtOrDefault(actionIndex - 1) : 0;
            var nextId = action.Publication.PublishedActions.OrderBy(a => a, new WBSComparer()).Select(p => p.PublishedActionId).ToList().ElementAtOrDefault(actionIndex + 1);

            var localizations = action.Publication.Localizations.ToDictionary(k => k.ResourceKey, v => v.Value);
            var documentationReferentials = await _referentialsService.GetDocumentationReferentials(action.Publication.ProcessId);
            localizations = ActionMapper.UpdateLocalizationLabelForDetail(localizations, documentationReferentials);
            var visibleColumns = ActionMapper.GetDetailDispositions(action.Publication, (PublishModeEnum)PublishModeFilter.Value);
            var values = new Dictionary<string, ActionColumnViewModel>();
            var actionHeaders = ActionMapper.GetDetailColumnHeader(visibleColumns, localizations);

            if (computeReadNext)
            {
                ViewBag.NextAction = nextId;
            }

            foreach (var setting in visibleColumns)
            {
                (List<RefsCollection> refs, List<CustomLabel> customLabel) = ActionMapper.BuildReferenceAndCustomLabel(action, localizations);
                var attribute = ReflectionHelper.GetPropertyValue(action, setting);
                values.Add(setting, ActionMapper.GetPublishedActionAttributes(action, attribute, setting, setting, localizations, refs, customLabel));
            }

            //Populate Action detail dispositions
            var detailsDisposition = new List<string>();
            if ((PublishModeEnum)PublishModeFilter.Value == PublishModeEnum.Formation)
            {
                if (publication.Formation_ActionDisposition.IsNotNullNorEmpty())
                {
                    detailsDisposition = publication.Formation_ActionDisposition.Split(',').ToList();
                }
            }
            else if ((PublishModeEnum)PublishModeFilter.Value == PublishModeEnum.Inspection)
            {
                if (publication.Inspection_ActionDisposition.IsNotNullNorEmpty())
                {
                    detailsDisposition = publication.Inspection_ActionDisposition.Split(',').ToList();
                }
            }
            
            

            var model = new GenericActionViewModel
            {
                ActionHeaders = actionHeaders,
                ActionId = action.PublishedActionId,
                Label = action.Label,
                ColumnValues = values,
                VideoExtension = action.CutVideo != null ? MimeMapping.GetMimeMapping(action.CutVideo.Extension) : null,
                VideoHash = action.CutVideo?.Hash,
                VideoExt = action.CutVideo?.Extension,
                ProcessId = action.Publication.ProcessId,
                ProcessLabel = action.Publication.Process.Label,
                PublicationVersion = action.Publication.Version,
                PublicationVersionIsMajor = action.Publication.IsMajor,
                PreviousActionId = previousId,
                NextActionId = nextId,
                IsKeyTask = action.IsKeyTask,
                PublishModeFilter = PublishModeFilter.Value,
                DetailActionDispositions = detailsDisposition
            };

            if (partial)
                return PartialView(model);

            return View(model);
        }
    }

}

Sources/KProcess.KL2.WebAdmin/Controllers/PublicationController.cs
using KProcess.KL2.JWT;
using KProcess.KL2.Languages;
using KProcess.KL2.WebAdmin.Authentication;
using KProcess.KL2.WebAdmin.Identity;
using KProcess.KL2.WebAdmin.Mapper;
using KProcess.KL2.WebAdmin.Models.Action;
using KProcess.KL2.WebAdmin.Models.Procedure;
using KProcess.KL2.WebAdmin.Models.Publications;
using KProcess.KL2.WebAdmin.Models.Users;
using KProcess.KL2.WebAdmin.Utils;
using KProcess.Ksmed.Business;
using KProcess.Ksmed.Business.ActionsManagement;
using KProcess.Ksmed.Models;
using KProcess.Ksmed.Models.Interfaces;
using KProcess.Ksmed.Security;
using Syncfusion.EJ.Export;
using Syncfusion.JavaScript.Models;
using Syncfusion.XlsIO;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace KProcess.KL2.WebAdmin.Controllers
{
    [CustomAuthorize(KnownRoles.Administrator, KnownRoles.Supervisor, KnownRoles.Evaluator, KnownRoles.Trainer, KnownRoles.Technician, KnownRoles.Operator, KnownRoles.Documentalist)]
    [SettingUserContextFilter]
    public class PublicationController : LocalizedController
    {
        readonly ITraceManager _traceManager;
        readonly IPrepareService _prepareService;
        readonly IApplicationUsersService _applicationUsersService;
        readonly IReferentialsService _referentialsService;

        //For populating Publications column in Excel Export
        List<UserReadPublicationViewModel> PublicationReadData;
        List<OperatorViewModel> UptodateOperatorsData;
        List<UserCompetencyViewModel> UserCompetencyData;
        List<GenericActionViewModel> PublishedActionsData;

        public int count;
        public int columnCounter;
        public string grid;

        public const int height = 250;
        public const int width = 350;
        public const double heightPoint = height * 72 / 96;
        public const double widthPoint = width / 7;

        public PublicationController(ITraceManager traceManager,
            IPrepareService prepareService,
            IApplicationUsersService applicationUsersService,
            IReferentialsService referentialsService,
            ILocalizationManager localizationManager
            )
            : base(localizationManager)
        {
            _traceManager = traceManager;
            _prepareService = prepareService;
            _applicationUsersService = applicationUsersService;
            _referentialsService = referentialsService;
        }

        // GET: Read publication
        public async Task<ActionResult> Index(int? processId, int? PublishModeFilter, bool partial = false)
        {
            try
            {
                PublishModeEnum filter = PublishModeEnum.Formation;
                if (PublishModeFilter.HasValue)
                {
                    filter = (PublishModeEnum)PublishModeFilter.Value;
                }
                INode[] publicationsTree = await _prepareService.GetPublicationsTree(filter);
                var nodes = new List<ProcedureNodeViewModel> { new ProcedureNodeViewModel { Id = "-1", Name = LocalizedStrings.GetString("All_Publications_Label"), ParentId = null, IsExpanded = true, HasChild = publicationsTree != null && publicationsTree.Any(), Sprite = "fa fa-folder" } };

                foreach (var publicationTree in Flatten(publicationsTree.ToList()))
                {
                    //There could be same value of processId and projectDirId where treebox in view cannot define clearly define Id and its parentId

                    if (publicationTree is ProjectDir)
                    {
                        var projectDir = publicationTree as ProjectDir;
                        nodes.Add(new ProcedureNodeViewModel
                        {
                            //projectDirId are named as : ex. projectDirId = 1, Id = d1
                            Id = "d" + projectDir.Id,
                            Name = projectDir.Name,
                            ParentId = projectDir.ParentId != null ? "d" + projectDir.ParentId : "-1",
                            IsExpanded = true,
                            HasChild = projectDir.Nodes != null && projectDir.Nodes.Any(),
                            Sprite = "fa fa-folder"
                        });
                    }
                    else if (publicationTree is Procedure)
                    {
                        var procedure = publicationTree as Procedure;
                        nodes.Add(new ProcedureNodeViewModel
                        {
                            //projectDirId are named as : ex. ProcessId = 1, Id = p1
                            Id = "p" + procedure.ProcessId,
                            Name = procedure.Label,
                            ParentId = procedure.ProjectDirId != null ? "d" + procedure.ProjectDirId : "-1",
                            HasChild = false,
                            LinkAttribute = Url.Action("Index", new { PublishModeFilter = (int)filter, processId = procedure.ProcessId }),
                            LinkAttributeFunction = "javascript:LoadPartial('" + Url.Action("Index", new { PublishModeFilter = (int)filter, processId = procedure.ProcessId, partial = true }) + "', '#pageContainer')",
                            Sprite = filter == PublishModeEnum.Formation ? "fa fa-graduation-cap" : filter == PublishModeEnum.Inspection ? "fa fa-check" : "fa fa-file-o"
                        });
                    }
                }

                var model = new PublicationManageViewModel
                {
                    TreeNode = nodes,
                    Publication = processId.HasValue ? await GetPublication(processId.Value, filter) : null,
                    PublicationType = filter.ToString()
                };
                if (partial)
                    return PartialView(model);
                return View(model);
            }
            catch (Exception ex)
            {
                _traceManager.TraceError(ex, ex.Message);
                return null;
            }
        }

        IEnumerable<INode> Flatten(IEnumerable<INode> e)
        {
            return e.SelectMany(c => Flatten(c.Nodes)).Concat(new[] { e });
        }

        async Task<PublicationViewModel> GetPublication(int processId, PublishModeEnum publishModeFilter)
        {
            try
            {
                var publication = await _prepareService.GetLastPublicationFiltered(processId, (int)publishModeFilter);
                var localizations = publication.Localizations.ToDictionary(k => k.ResourceKey, v => v.Value);

                var model = new PublicationViewModel
                {
                    PublicationId = publication.PublicationId.ToString(),
                    ProcessId = publication.ProcessId,
                    Label = publication.Process.Label,
                    Actions = new List<GenericActionViewModel>(),
                    PublishModeEnum = (int)publishModeFilter,
                    Version = publication.Version,
                    IsMajor = publication.IsMajor,
                    ReferentialsUsed = new List<ActionValueViewModel>()
                };

                if ((publishModeFilter == PublishModeEnum.Formation && publication.Formation_Disposition != null)
                    || publishModeFilter == PublishModeEnum.Inspection && publication.Inspection_Disposition != null)
                {
                    var visibleColumns = PublicationSfDataGridXml.GetVisibleActionColumns(publication, publishModeFilter);
                    model.ActionsColumnCount = visibleColumns.Count();
                    model.ActionHeaders = ActionMapper.GetColumnHeader(visibleColumns, localizations);
                    model.ActionHeaderModels = ActionMapper.GetColumnHeaderWithValue(visibleColumns, localizations);
                    var refsUsed = new List<ActionValueViewModel>();

                    foreach (var action in publication.PublishedActions)
                    {
                        (List<RefsCollection> refs, List<CustomLabel> customLabel) = ActionMapper.BuildReferenceAndCustomLabel(action, localizations);
                        var values = new Dictionary<string, ActionColumnViewModel>();
                        foreach (var setting in visibleColumns)
                        {
                            values.Add(setting.MappingName,
                                ActionMapper.GetPublishedActionAttributes(
                                    action,
                                    ReflectionHelper.GetPropertyValue(action, setting.MappingName),
                                    setting.HeaderText,
                                    setting.MappingName,
                                    localizations,
                                    refs,
                                    customLabel));
                            var refCollection = ActionMapper.GetActionReferentials(refs, setting.MappingName, localizations);
                            if (refCollection.Count > 0)
                            {
                                refsUsed.AddRange(refCollection.Where(_ => refsUsed.All(r => r.ReferentialId != _.ReferentialId)));
                            }
                        }
                        model.Actions.Add(new GenericActionViewModel
                        {
                            ActionId = action.PublishedActionId,
                            ColumnValues = values,
                            PublishModeFilter = (int)publishModeFilter,
                            PublicationVersion = action.Publication.Version,
                            PublicationVersionIsMajor = action.Publication.IsMajor,
                            IsKeyTask = action.IsKeyTask,
                            IsGroup = WBSHelper.HasChildren(action, publication.PublishedActions)

Sources/KProcess.KL2.WebAdmin/Views/Action/Details.cshtml
@using KProcess.KL2.WebAdmin.Models.Action;
@using System.Web.Configuration;
@using KProcess;
@using KProcess.KL2.Languages;

@model GenericActionViewModel

@{
    var LocalizedStrings = (ILocalizationManager)ViewBag.LocalizedStrings;
    var WBS = Model.ColumnValues["WBS"].Values.Select(v => v.Value).FirstOrDefault();
}

<style>
    .innerContainer {
        display: flex;
        flex-direction: column;
        height: 100%;
    }

    .innerContent {
        flex: 1;
        min-height: 0px;
    }

    .topMargin {
        margin-top: 10px;
    }
</style>

<div class="innerContainer">
    <div class="row">
        <div class="col-md-12">
            <button type="button" class="btn bg-light-blue btn-flat" onclick="LoadPartial('@Url.Action("Index", "Publication", new { PublishModeFilter = Model.PublishModeFilter, processId = Model.ProcessId, partial = true})', '#pageContainer')"><i class="fa fa-angle-double-left"></i> @LocalizedStrings.GetString("Back")</button>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>@($"{Model.ProcessLabel} (v{Model.PublicationVersion})")</h2>
        </div>
    </div>
    <div class="innerContent" style="display: flex; flex-direction: column;">
        <div class="row">
            <div class="col-md-3">
                @if (Model.PreviousActionId != 0)
                {
                    <button class="btn btn-app text-left" onclick="LoadPartial('@Url.Action("Details","Action", new { PublishModeFilter = Model.PublishModeFilter, id = Model.PreviousActionId, partial = true })', '#pageContainer')">
                        <i class="fa fa-arrow-circle-left"></i>@LocalizedStrings.GetString("Common_Previous")
                    </button>
                }
            </div>

            <div class="col-md-7">
                <h3 class="text-center">
                    <span class="badge badge-secondary">@WBS</span> @Model.Label
                    @if (Model.IsKeyTask)
                    {
                        <span class="badge badge-secondary" title="Key Task" style="background-color: darksalmon">!</span>
                    }

                </h3>
            </div>
            <div class="col-md-2">
                @if (Model.NextActionId != 0)
                {
                    <button class="btn btn-app pull-right" onclick="LoadPartial('@Url.Action("Details","Action", new { PublishModeFilter = Model.PublishModeFilter, id = Model.NextActionId, partial = true })', '#pageContainer')">
                        <i class="fa fa-arrow-circle-right"></i>@LocalizedStrings.GetString("Common_Next")
                    </button>
                }
            </div>
        </div>
        <div class="row innerContent">
            <div class="col-md-6" style="height: 100%;overflow: auto;">
                @{
                    int lineCounter = 0;
                }
                @foreach (var columnKeyPairValue in Model.ColumnValues.Where(_ => _.Value?.Values?.Any() == true && _.Value.Values.All(v => !string.IsNullOrEmpty(v.Value))))
                {
                    if (columnKeyPairValue.Key != "WBS" && columnKeyPairValue.Key != "Label" && (Model.DetailActionDispositions.Contains(columnKeyPairValue.Key) || columnKeyPairValue.Key == "Thumbnail"))
                    {
                        if (lineCounter == 0)
                        {
                            @Html.Raw("<div class=\"row\">");
                        }
                        <div class="col-md-6 text-center">
                            <div class="e-card topMargin">
                                <div class="e-card-header">
                                    <div class="e-card-header-caption">
                                        <div class="e-card-header-title"><label><b>@Model.ActionHeaders.GetOrDefault(columnKeyPairValue.Key, string.Empty)</b></label></div>
                                    </div>
                                </div>
                                <div class="e-card-content">
                                    @foreach (var value in columnKeyPairValue.Value.Values)
                                    {
                                        <div>
                                            @switch (value.Type)
                                            {
                                                case "Text":
                                                    <p style="word-wrap:break-word;overflow:hidden;">
                                                        @if (value.Quantity != null)
                                                        {
                                                            <span class="badge bg-gray" style="margin:3px;margin-bottom:5px;">x@(value.Quantity)</span>
                                                        }
                                                        @value.Value
                                                    </p>
                                                    break;
                                                case "Image":
                                                    if (value.Quantity != null)
                                                    {
                                                        <span class="badge bg-gray" style="margin:3px;margin-bottom:5px;">x(@value.Quantity)</span><span>x</span>
                                                    }
                                                    <img height="100" class="imagePopUp" src="@Html.Raw(WebConfigurationManager.AppSettings["FileServerUri"])/GetFile/@value.FileHash@value.FileExt" title="@value.Value" onclick="popUpImage(this)">
                                                    break;
                                                case "File":
                                                    <div><a target="_blank" href="@Html.Raw(WebConfigurationManager.AppSettings["FileServerUri"])/GetFile/@value.FileHash@value.FileExt">@value.Value</a></div>
                                                    break;
                                            }
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                        if (lineCounter == 1)
                        {
                            @Html.Raw("</div>");
                        }
                        if (++lineCounter == 2)
                        {
                            lineCounter = 0;
                        }
                    }
                }
                @if (lineCounter == 1)
                {
                    @Html.Raw("</div>");
                }
            </div>
            <div class="col-md-6" style="text-align:center; height: 100%; display: flex; flex-direction: column;">
                <div class="panel panel-default" style="flex: 1; min-height: 0px; display: flex; flex-direction: column;">
                    <div class="panel-heading">
                        <label><b>@LocalizedStrings.GetString("Video")</b></label>
                    </div>
                    <div class="panel-body" style="flex: 1; min-height: 0px;">
                        @if (!string.IsNullOrEmpty(Model.VideoHash))
                        {
                            <video id="video" controls autoplay="" style="max-width:100%;max-height:100%;width:100%;">
                                <source src="@Html.Raw(WebConfigurationManager.AppSettings["FileServerUri"])/Stream/@Model.VideoHash@Model.VideoExt">
                            </video>
                        }
                        else
                        {
                            <p>@LocalizedStrings.GetString("NoVideo")</p>
                        }
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>

<script>
    docReady(function () {
        // Start the video by default
        //$('#video').get(0).play();

        @if (ViewBag.ComputeReadNext == true && ViewBag.NextAction > 0)
        {
            <text>
            $('#video').on('ended', function () {
                var nextVideoUrl = '@Url.Action("Details", "Action", new { PublishModeFilter = ViewBag.publishModeFilter, @Id = ViewBag.NextAction, ComputeReadNext = ViewBag.ComputeReadNext, partial = true })';
                nextVideoUrl = nextVideoUrl.replace(/&amp;/g, '&');
                LoadPartial(nextVideoUrl, '#pageContainer');
            });
            </text>
        }
        setIsRefreshing(false);
    });

    function getParameterByName(name, url) {
        if (!url) url = window.location.href;
        name = name.replace(/[\[\]]/g, "\\$&");
        var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
            results = regex.exec(url);
        if (!results) return null;
        if (!results[2]) return '';
        return decodeURIComponent(results[2].replace(/\+/g, " "));
    }
</script>